algoritmo "Idade Para votar"
// Autor : Miguel Caparroz
// Data : 14/04/2026

var
//variavel
  idade:real
inicio
// Seção de Comandos

   escreva("Informe sua idade:")
   leia(idade)


//calculos
        se idade = 16 entao
   escreval("Voto opcional")
   senao
   se idade = 17 entao
   escreval("Voto opcional")
   senao
   se idade>= 70 entao
   escreval("Voto opcional")
   senao
   escreval("Voto obrigatório")


   fimse
fimalgoritmo
   fimse


