algoritmo "Soma de 3 numeros"
// Autor : Miguel Caparroz
// Data : 13/04/2026

var
//variavel
   soma, n1, n2, n3:real
inicio
// Seção de Comandos 
   escreva("Informe o primeiro numero da soma:")
   leia(n1)
   escreva("Informe o segundo numero da soma:")
   leia(n2)
   escreva("Informe o terceiro numero da soma:")
   leia(n3)
   
//calculos
          soma<-n1+n2+n3
          
escreval("A soma dos três numeros é: ",soma)
   
fimalgoritmo
